# Generated by Django 4.0.1 on 2022-01-18 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dddungeon_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
    ]
